module.exports = {
  EMPTY_STATUS: 0
  OPENING_PAYLOAD: 1
  CLOSING_PAYLOAD: 2
  CLOSED_TAG: 3
  OPENING_TAG: 4
  CLOSING_TAG: 5
  OPENING_COMMENT: 6
  CLOSING_COMMENT: 7
  OPENING_CDATA: 8
  CLOSING_CDATA: 9
  TAG_NAME: 10
  ATTRIBUTE_NAME: 11
  ATTRIBUTE_VALUE: 12
  SINGLE_QUOTED_ATTRIBUTE_VALUE: 13
  DOUBLE_QUOTED_ATTRIBUTE_VALUE: 14
  TAG_CONTENTS: 15
}
# {EMPTY_STATUS,OPENING_PAYLOAD,CLOSING_PAYLOAD,CLOSED_TAG,OPENING_TAG,CLOSING_TAG,OPENING_COMMENT,CLOSING_COMMENT,OPENING_CDATA,CLOSING_CDATA,TAG_NAME,ATTRIBUTE_NAME,ATTRIBUTE_VALUE,SINGLE_QUOTED_ATTRIBUTE_VALUE,DOUBLE_QUOTED_ATTRIBUTE_VALUE,TAG_CONTENTS} = require './states'
