module.exports = {
  EMPTY_STATUS: 0x0
  BEGIN_PAYLOAD: 0x1
  END_PAYLOAD: 0x2
  TAG_HEAD: 0x4
  PREFIXED: 0x8
  BEGIN_TAG: 0x10
  READY_FOR_ATTRIBUTE: 0x20
  END_TAG: 0x40
  BEGIN_ATTRIBUTE: 0x80
  SPACE: 0x100
  DOUBLE_QUOTTED: 0x200
  SINGLE_QUOTTED: 0x400
  END_ATTRIBUTE: 0x800
  BEGIN_COMMENT: 0x1000
  END_COMMENT: 0x2000
  BEGIN_CDATA: 0x4000
  END_CDATA: 0x8000
  LOW_PRIORITY_CONTENT: 0x10000
  MASK: 0xFFFFFFFF
}
# {EMPTY_STATUS,BEGIN_PAYLOAD,END_PAYLOAD,TAG_HEAD,PREFIXED,BEGIN_TAG,READY_FOR_ATTRIBUTE,END_TAG,BEGIN_ATTRIBUTE,SPACE,DOUBLE_QUOTTED,SINGLE_QUOTTED,END_ATTRIBUTE,BEGIN_COMMENT,END_COMMENT,BEGIN_CDATA,END_CDATA,LOW_PRIORITY_CONTENT,MASK} = require './states'
